### PR TITLE
Update dependencies + add README

### PR DESCRIPTION
**Pull request by sectore**

### CODE REVIEW

**Comment by ethul** [comment]
Thanks for the update!

Looks great. However, would you be okay removing the `bower` dev dependency in the package.json? I think it is pretty safe to assume that the user has bower installed if they are using PureScript.

Thanks!

**Comment by sectore** [comment]
Sure, but what about all users new to PureScript? I thought that's why PureScript is also a dependency in `package.json`.

**Comment by ethul** [comment]
I think it is okay not to explicitly depend on bower. The purescript getting started guide walks through a development setup and mentions installing bower (http://www.purescript.org/learn/getting-started/). Granted, it also mentions installing purescript globally as a package. However, the reason that it is included in the example as a dev dependency is because the example requires that purescript be at least at version 0.10. Otherwise the example won't work. There isn't really a specific bower version dependency, so I think it works to not have it in the package.json.

**Comment by ethul** [comment]
Thanks!

**Pull request merged**
